project/social/__init__.py
from flask import Blueprint

social_blueprint = Blueprint('social', __name__, template_folder='templates')

from . import routes, events

project/social/routes.py
from config import MAX_INACTIVE_MINS
from project.models import *
from flask import render_template, request, redirect, url_for, session
from flask_login import login_required, current_user
from project import db
from datetime import datetime, timedelta

from . import social_blueprint


def get_unread_messages():
    res = 0
    
    for chat in current_user.chats:
        timestamp = Timestamp.query.filter_by(user_id=current_user.id, chat_id=chat.id).first()
        if timestamp == None:
            res += len(chat.messages)
        else:
            unread_messages_number = Message.query.filter(Message.chat_id == chat.id, Message.date >= timestamp.timestamp).order_by(Message.date).count()
            res += unread_messages_number
    
    return res


@social_blueprint.route('/', methods=['GET', 'POST'])
@login_required
def home():
    total_unread_messages = get_unread_messages()
    
    if request.method == 'GET':
        return render_template('home.html', 
                               username=current_user.username, 
                               total_unread_messages=total_unread_messages)

    username = request.form['search_field'][:min(15, len(request.form['search_field']))]
    
    if username == current_user.username:
        return redirect(url_for('users.my_profile'))
    
    user = User.query.filter_by(username=username).first()
    
    if user == None:
        return render_template('home.html', 
                            username=current_user.username,
                            span_class='invalid', 
                            message='No user was found :(',
                            total_unread_messages=total_unread_messages)
    
    return render_template('home.html', 
                            username=current_user.username,
                            found_username=user.username,
                            found_id=user.id,
                            is_friend=user in current_user.friends,
                            total_unread_messages=total_unread_messages,
                            is_online=((datetime.utcnow() - user.last_activity) < timedelta(minutes=MAX_INACTIVE_MINS)))


@social_blueprint.route('/messages/chat/<int:id>')
@login_required
def chat(id):
    total_unread_messages = get_unread_messages()
    
    chat = Chat.query.get(id)
    
    if chat == None or chat not in current_user.chats:
        return redirect(url_for('social.messages'))
    
    session['current_chat_id'] = id
    
    hours_delta = timedelta(hours=int(request.cookies.get('timezoneOffset', 0)))
    
    timestamp = Timestamp.query.filter_by(user_id=current_user.id, chat_id=id).first()
    
    if timestamp == None:
        seen_messages = []
        unread_messages = chat.messages
    else:
        seen_messages = Message.query.filter(Message.chat_id == id, Message.date < timestamp.timestamp).order_by(Message.date)
        unread_messages = Message.query.filter(Message.chat_id == id, Message.date >= timestamp.timestamp).order_by(Message.date)
    
    if chat.users[0].id == current_user.id:
        other_user = chat.users[1]
    else:
        other_user = chat.users[0]
    
    is_online = (datetime.utcnow() - other_user.last_activity) < timedelta(minutes=MAX_INACTIVE_MINS)
    
    page = render_template('chat.html', 
                        seen_messages=list(seen_messages), 
                        unread_messages=list(unread_messages),
                        current_user=current_user,
                        hours_delta=hours_delta,
                        is_online=is_online,
                        total_unread_messages=total_unread_messages)
    
    if timestamp == None:
        db.session.add(Timestamp(user_id=current_user.id, 
                                chat_id=chat.id,
                                timestamp=datetime.utcnow()))
    else:
        timestamp.timestamp = datetime.utcnow()

    db.session.commit()
    
    return page


@social_blueprint.route('/messages')
@login_required
def messages():   
    total_unread_messages = 0
     
    chats_with_unread_messages = []
    for chat in current_user.chats:
        if chat.users[0].id == current_user.id:
            other_user = chat.users[1]
        else:
            other_user = chat.users[0]
        
        is_online = (datetime.utcnow() - other_user.last_activity) < timedelta(minutes=MAX_INACTIVE_MINS)
        
        timestamp = Timestamp.query.filter_by(user_id=current_user.id, chat_id=chat.id).first()
        if timestamp == None:
            chats_with_unread_messages.append((chat, len(chat.messages), is_online))
            total_unread_messages += len(chat.messages)
        else:
            unread_messages_number = Message.query.filter(Message.chat_id == chat.id, Message.date >= timestamp.timestamp).order_by(Message.date).count()
            chats_with_unread_messages.append((chat, unread_messages_number, is_online))
            total_unread_messages += unread_messages_number
    
    return render_template('messages.html', 
                           chats_with_unread_messages=chats_with_unread_messages,
                           total_unread_messages=total_unread_messages)


@social_blueprint.route('/start-chat/<int:other_id>')
@login_required
def start_chat(other_id):
    other_user = User.query.get(other_id)
    
    if other_user == None or other_id == current_user.id:
        return redirect(url_for('social.home'))
    
    for chat in current_user.chats:
        if chat.users[0].id == other_id or chat.users[1].id == other_id:
            return redirect(url_for('social.chat', id=chat.id))
    
    new_chat = Chat()
    
    db.session.add(new_chat)
    new_chat.users.append(current_user)
    new_chat.users.append(other_user)
    
    db.session.commit()
    
    return redirect(url_for('social.chat', id=new_chat.id))


@social_blueprint.route('/friends')
@login_required
def friends():
    total_unread_messages = get_unread_messages()
    
    items = []
    
    for friend in current_user.friends:
        is_online = (datetime.utcnow() - friend.last_activity) < timedelta(minutes=MAX_INACTIVE_MINS)
        items.append((friend, is_online))
    
    return render_template('friends.html', 
                           items=items,
                           total_unread_messages=total_unread_messages)


@social_blueprint.route('/add-friend/<int:friend_id>')
@login_required
def add_friend(friend_id):
    if (friend_id == current_user.id):
        return redirect(url_for('social.home'))
    
    friend_user = User.query.get(friend_id)
    
    if (friend_user == None or friend_user in current_user.friends):
        return redirect(url_for('social.friends'))
    
    current_user.friends.append(friend_user)
    friend_user.friends.append(current_user)
    
    db.session.commit()
    
    return redirect(url_for('social.friends'))


@social_blueprint.route('/remove-friend/<int:friend_id>')
@login_required
def remove_friend(friend_id):
    if friend_id == current_user.id:
        return redirect(url_for('social.home'))
    
    friend_user = User.query.get(friend_id)
    
    if friend_user == None or not friend_user in current_user.friends:
        return redirect(url_for('social.friends'))
    
    current_user.friends.remove(friend_user)
    friend_user.friends.remove(current_user)
    
    db.session.commit()
    
    return redirect(url_for('social.friends'))

project/social/templates/chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Chat</title>
    <link id="favicon" rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 110 100%22><text y=%22.9em%22 font-size=%2290%22>🍉</text></svg>">

    <script defer src="https://code.jquery.com/jquery-3.6.0.min.js" 
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
    crossorigin="anonymous"></script>

    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" 
        integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" 
        crossorigin="anonymous">
    </script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cambay">

    <link rel="stylesheet" href="/static/css/base.css">
    <script defer src="/static/js/main_script.js"></script>
    <script defer src="/static/js/validation.js"></script>

</head>

<body>
    <button id="show-menu" class="mobile-show-menu">≡</button>

    <div id="navbar" class="navbar">
        <ul>
            <li><a href="{{ url_for('social.home') }}">Home</a></li>

            {% if total_unread_messages > 0 %}
                <li><a id="messages-link" class="messages-link" style="width:auto;" href="{{ url_for('social.messages') }}">Messages <span id="unread-navbar" class="unread-dot">{{ total_unread_messages }}</span></a></li>
            {% else %}
                <li><a id="messages-link" class="messages-link" href="{{ url_for('social.messages') }}">Messages</a></li>
            {% endif %}
            
            <li><a href="{{ url_for('social.friends') }}">Friends</a></li>
             {% if current_user.is_admin %}
                 <li><a href="/admin">Admin panel</a></li>
             {% endif %}
             <li><a href="{{ url_for('users.my_profile') }}">Profile</a></li>
             <li><a class="logout" href="{{ url_for('users.logout') }}">Log Out</a></li>
        </ul>
        <hr>
    </div>
    <div class="main-page">
        <div class="chat" id="chat">
            <h2>Chat</h2>
            {% if unread_messages|length == 0 and seen_messages|length == 0 %}
                <h3 id="no-msg" class="no-msg">No messages yet :(</h3>
            {% else %}
            
                {% for message in seen_messages %}
                    {% if message.user_id == current_user.id %}
                        <div class="self-message">
                            <p class="self-text">
                                <span class="self-name">{{ message.user.username }}:</span>
                                {{ message.text }}
                            </p>
                        </div>
                        <p class="self-msg-time">
                            {{ (message.date - hours_delta).strftime("%d/%m/%Y %H:%M:%S") }}
                        </p>
                    {% else %}
                        <div class="other-message">
                            <p class="other-text">
                                {% if is_online %}
                                    <span class="online-dot">•</span>
                                {% else %}
                                    <span class="offline-dot">•</span>
                                {% endif %}
                                <span class="other-name">
                                    {{ message.user.username }}: 
                                </span>
                                {{ message.text }}
                            </p>
                        </div>
                        <p class="other-msg-time">
                            {{ (message.date - hours_delta).strftime("%d/%m/%Y %H:%M:%S") }}
                        </p>
                    {% endif %}
                {% endfor %}
        
                {% if unread_messages|length > 0 %}
                    <div id="unread-msg" class="unread-delimiter">
                        <p class="unread-msg-line-text">Unread Messages</p>
                        <hr class="unread-line">
                        <hr class="unread-line">
                    </div>
                {% endif %}
        
                {% for message in unread_messages %}
                    <div class="other-message">
                        <p class="other-text">
                            {% if is_online %}
                                <span class="online-dot">•</span>
                            {% else %}
                                <span class="offline-dot">•</span>
                            {% endif %}
                            <span class="other-name">
                                {{ message.user.username }}: 
                            </span>
                            {{ message.text }}
                        </p>
                    </div>
                    <p class="other-msg-time">
                        <span class="new-badge">NEW</span>
                        {{ (message.date - hours_delta).strftime("%d/%m/%Y %H:%M:%S") }}
                    </p>
                {% endfor %}
            {% endif %}
        </div>
        
        <div class="input-area">
            <form id="message_form" method="POST">
                <textarea type="text" id="message_text_area" class="message-input" maxlength="1000" placeholder="Type here..."></textarea> 
                <p class="msg-limit-verdict" id="server_verdict">Limit 1000 characters</p>
                <input id="send-button" class="send-button" value="Send" type="submit" />
            </form>
        </div>
    </div>
</body>
</html>

project/social/templates/friends.html
{% extends 'base.html' %}

{% block title %}
Friends
{% endblock %}

{% block body %}

<div class="friends">
    {% if items|length > 0 %}
        <h2>Friends of {{ current_user.username }}</h2>

        <hr class="friend-delimiter">

        {% for item in items %}
            {% set friend = item[0] %}
            {% set is_online = item[1] %}
            <div class="friend">
                <p class="online-status">
                    Status: 
                    {% if is_online %}
                        <span class="online">online</span> 
                    {% else %}
                        <span class="offline">offline</span> 
                    {% endif %}
                </p>

                <p class="friend-name">
                    Username: 
                    <span>{{ friend.username }}</span>
                </p>
            </div>

            <div class="manage-friend">
                <a href="{{ url_for('social.start_chat', other_id=friend.id) }}" class="start-chat">Start Chat</a>
                <a href="{{ url_for('social.remove_friend', friend_id=friend.id) }}" class="remove-friend">Remove friend</a>
            </div>

            <hr class="friend-delimiter">

        {% endfor %}
    {% else %}
        <div class="no-friends-msg">
            <p>Oh no, you have no friends :(</p>
        </div>
    {% endif %}
</div>

{% endblock %}

project/social/templates/home.html
{% extends 'base.html' %}

{% block title %}
Home page
{% endblock %}

{% block body %}
<div class="greet">
    <p>Welcome, {{ username }}!</p>
</div>

<div class="search">
    {% if message|length > 0 %}
        <p class="{{ span_class }}">{{ message }}</p>
    {% endif %}
    <form autocomplete="off" method="POST">
        <input maxlength="15" id="search_field" name="search_field" autocomplete="off" placeholder="Search users by username...">
        <p id="find-verdict" class="invalid-find-name">Username was not found</p>
        <div id="found-user-list" class="found-user-list"></div>
        <button class="submit" id="find-button">Find</button>
    </form>

    {% if found_username|length > 0 %}

        <div class="found-user">
            <h2>Found user:</h2>

            {% if is_online %}
                <h3>Status: <span class="online">online</span></h3>
            {% else %}
                <h3>Status: <span class="offline">offline</span></h3>
            {% endif %}

            <h3 class="username">Username: {{ found_username }}</h3>

            <a href="{{ url_for('social.start_chat', other_id=found_id) }}" class="start-chat">Start Chat</a>

            {% if is_friend %}
                <p class="already-friend">Already friend</p>
            {% else %}
                <a href="{{ url_for('social.add_friend', friend_id=found_id) }}" class="add-friend">Add Friend</a>
            {% endif %}
        </div>

    {% endif %}
</div>

{% endblock %}

project/social/templates/messages.html
{% extends 'base.html' %}

{% block title %}
Messages
{% endblock %}

{% block body %}
<div class="chats">
    <h2>Chats</h2>

    {% if chats_with_unread_messages|length > 0 %}
        {% for item in chats_with_unread_messages %}
            {% set chat = item[0] %}
            {% set unread_messages_number = item[1] %}
            {% set is_online = item[2] %}

            <div id="chat{{ chat.id }}">
                {% if chat.users[0].id == current_user.id %}
                    {% if is_online %}
                        <p class="online-dot">•</p>
                    {% else %}
                        <p class="offline-dot">•</p>
                    {% endif %}

                    <a class="chat-link" href="{{ url_for('social.chat', id=chat.id) }}">{{ chat.users[1].username }}</a>
                    
                {% else %}
                    {% if is_online %}
                        <p class="online-dot">•</p>
                    {% else %}
                        <p class="offline-dot">•</p>
                    {% endif %}
                    <a class="chat-link" href="{{ url_for('social.chat', id=chat.id) }}">{{ chat.users[0].username }}</a>
                    
                {% endif %}

                {% if unread_messages_number > 0 %}
                    <p class="unread-msg"> <span id="unread_msg_chat{{ chat.id }}" class="unread-msg">{{ unread_messages_number }}</span> unread</p>
                {% endif %}
            </div>
            
        {% endfor %}
    {% else %}
        <h2 class="text-center">No chats yet :(</h2>
    {% endif %}
</div>

{% endblock %}