project/users/__init__.py
from flask import Blueprint

users_blueprint = Blueprint('users', __name__, template_folder='templates')

from . import routes, events

project/users/routes.py
from project.models import *
from flask import render_template, request, redirect, url_for, session, make_response
from werkzeug.security import check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from project import db

from . import users_blueprint


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        
        valid_username = not username is None and len(username) > 2 and len(username) < 16
        valid_password = not password is None and len(password) > 2 and len(username) < 81
        
        if valid_username and valid_password:
            
            db_user = User.query.filter_by(username=username).first()
            
            if db_user == None or not check_password_hash(db_user.password, password):
                return render_template('login.html', 
                                    span_class='invalid', 
                                    message='Wrong username or password',
                                    prev_username=username)
            login_user(db_user)
            response = make_response(redirect(url_for('social.home')))
            response.set_cookie('username', username, max_age=60*60*24*365)
            return response
            
        return render_template('login.html',
                            span_class='invalid',
                            message='Invalid username or password')
    else:
        if ('message' in session.keys() and 'span_class' in session.keys() and 
            len(session['message']) > 0 and len(session['span_class']) > 0):
            
            message = session.pop('message', '')
            span_class = session.pop('span_class', '')
            
            return render_template('login.html', 
                span_class=span_class, 
                message=message)

        return render_template('login.html')


@users_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        
        valid_username = not username is None and len(username) > 2 and len(username) < 16
        valid_password = not password is None and len(password) > 2 and len(username) < 81
        
        if valid_username and valid_password:
            new_user = User(username=username, 
                            password=password)
            
            existing_user = User.query.filter_by(username=username).first()
            
            if existing_user:
                return render_template('signup.html', 
                                    span_class='invalid', 
                                    message='Username already exists',
                                    prev_username=username)
                
            db.session.add(new_user)
            db.session.commit()
            session['message'] = "You've registered account successfully"
            session['span_class'] = 'valid'
            return redirect(url_for('users.login'))
            
        return render_template('signup.html',
                            span_class='invalid',
                            message='Invalid username or password')
        
    return render_template('signup.html')


@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users_blueprint.route('/my-profile', methods=['GET', 'POST'])
@login_required
def my_profile():
    
    from project.social.routes import get_unread_messages
    
    total_unread_messages = get_unread_messages()
    
    user = User.query.get(current_user.id)
    
    if request.method == 'GET':
        return render_template('my_profile.html', 
                               user=user,
                               total_unread_messages=total_unread_messages)
    else:
        username = request.form['username']
        valid_username = not username is None and len(username) > 2 and len(username) < 16
        
        existing_username = User.query.filter_by(username=username).first()
        
        if existing_username:
            return render_template('my_profile.html', 
                                span_class='invalid', 
                                message='Username already exists',
                                user=user,
                                total_unread_messages=total_unread_messages)
        
        if valid_username:
            user.username = username
            db.session.commit()
            
            response = make_response(redirect(url_for('users.my_profile')))
            response.set_cookie('username', username, max_age=60*60*24*365)
            
            return response
                    
        return render_template('my_profile.html',
                        span_class='invalid',
                        message='Invalid username',
                        user=user,
                        total_unread_messages=total_unread_messages)


@users_blueprint.route('/delete')
@login_required
def delete():
    user = User.query.get(current_user.id)
    
    for friend in user.friends:
        user.friends.remove(friend)
        friend.friends.remove(user)
    
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('users.login'))

project/users/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Login</title>
    <link id="favicon" rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 110 100%22><text y=%22.9em%22 font-size=%2290%22>🍉</text></svg>">

    <script defer src="https://code.jquery.com/jquery-3.6.0.min.js" 
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
    crossorigin="anonymous"></script>

    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.min.js"
    integrity="sha512-eVL5Lb9al9FzgR63gDs1MxcDS2wFu3loYAgjIH0+Hg38tCS8Ag62dwKyH+wzDb+QauDpEZjXbMn11blw8cbTJQ=="
    crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cambay">

    <link rel="stylesheet" href="/static/css/login.css">
    <script defer src="/static/js/validation.js"></script>
</head>
<body>
    <div class="background">
        <div class="box">
            <h1>LOGIN</h1>
            <p class="text-muted">Please enter your login and password!</p>

            <form autocomplete="off" method="POST">
                <p class="verdict {{ span_class }}" name="server_verdict">{{ message }}</p>

                <input type="text" onkeyup="validate()" name="username" id="username" value="{{ prev_username }}" placeholder="Username" maxlength="15" required>
                <p class="verdict" id="username_verdict"></p>

                <input type="password" onkeyup="validate()" name="password" id="password" placeholder="Password" maxlength="80" required> 
                <p class="verdict" id="password_verdict"></p>

                <a class="signup" href="{{ url_for('users.signup') }}">Sign Up if you don't have an account</a>

                <button class="submit" id="submit">Login</button>
            </form>
        </div>
    </div>
</body>
</html>

project/users/templates/my_profile.html
{% extends 'base.html' %}

{% block title %}
Profile
{% endblock %}

{% block body %}
    <div class="edit-area">
        <h2 class="header">Profile Information</h2>

        <h3>Edit username: </h3>
        
        <form class="edit-form" autocomplete="off" method="POST">
            <input class="username-input" type="text" onkeyup="validate()" name="username" id="username" value="{{ user.username }}" placeholder="Username" maxlength="15">
            <input class="edit-button" type="submit" id="submit" value="Edit">
            <span class="{{ span_class }}" id="username_verdict">{{ message }}</span>
        </form>

        <a href="/delete" class="remove-friend">Delete account</a>
    </div>
{% endblock %}

project/users/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Signup</title>
    <link id="favicon" rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 110 100%22><text y=%22.9em%22 font-size=%2290%22>🍉</text></svg>">

    <script defer src="https://code.jquery.com/jquery-3.6.0.min.js" 
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
    crossorigin="anonymous"></script>

    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.min.js"
    integrity="sha512-eVL5Lb9al9FzgR63gDs1MxcDS2wFu3loYAgjIH0+Hg38tCS8Ag62dwKyH+wzDb+QauDpEZjXbMn11blw8cbTJQ=="
    crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cambay">

    <link rel="stylesheet" href="/static/css/login.css">
    <script defer src="/static/js/validation.js"></script>
</head>
<body>
    <div class="signup-background">
        <div class="box">
            <h1>SIGN UP</h1>
            <p class="text-muted" style="margin-bottom: 3%;">Please enter your login and password!</p>

            <form autocomplete="off" method="POST">
                <input type="text" onkeyup="validate()" name="username" id="username" value="{{ prev_username }}" placeholder="Username" maxlength="15" required>
                <p class="verdict {{ span_class }}" id="username_verdict">{{ message }}</p>

                <input type="password" onkeyup="validate()" name="password" id="password" placeholder="Password" maxlength="80" required> 
                <p class="verdict" id="password_verdict"></p>

                <a class="signup" href="{{ url_for('users.login') }}">Back to login</a>

                <button class="submit" type="submit" id="submit">Sign Up</button>
            </form>
        </div>
    </div>
</body>
</html>